version: "2"

services:
  evklid-trainer:
    build: ./evklid-trainer/
    container_name: evklid-trainer
    restart: always
    volumes:
      - /srv/edu/online-modules/evklid-trainer:/usr/discrete-eltech
    restart: always

  atp-system:
    build: ./atp-system/
    container_name: atp-system
    restart: always
    volumes:
      - /srv/edu/online-modules/atp-system:/usr/atp-system
    restart: always

  apache-php:
    build: ./apache-php/
    container_name: edu-shell
    restart: always
    volumes:
      - /home/dmitriy/Projects/PhpstormProjects/edu-shell:/srv/www/edu
    restart: always

#  boolean-solver:
#    build: ./boolean-solver/
#    container_name: boolean-solver
#    restart: always
#    volumes:
#      - /srv/docker/online-modules/boolean-solver:/usr/boolean-solver
#
#  boolean-clases:
#    build: ./boolean-classes/
#    container_name: boolean-classes
#    restart: always
#    volumes:
#      - /srv/docker/online-modules/boolean-classes:/var/www/boolean-classes

  nginx-proxy:
    build: ./nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/edu/edu-modules:/www
      - /srv/edu/offline-modules:/www/modules
    restart: always
#
  mongodb:
    build: ./mongo/
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - /srv/mongo/evklid-trainer:/data/db
    restart: always

  mysql:
    build: ./mysql/
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edu-shell
      MYSQL_USER: edu
      MYSQL_PASSWORD: edu
    volumes:
      - /srv/mysql:/var/lib/mysql
    restart: always

networks:
  default:
    external:
      name: nginx-proxy