version: '2'
services:
  evklid-trainer:
    build: ./evklid-trainer/
    container_name: evklid-trainer
    restart: always
    volumes:
      - '/srv/edu/online-modules/evklid-trainer:/usr/discrete-eltech'
    networks:
      - backend
      - frontend

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    environment:
      - NGINX_HOST=konstantinov.com.ru
      - NGINX_PORT=80
    volumes:
      - '/srv/edu/edu-modules:/www/edu'
      - '/srv/edu/offline-modules:/www/edu/modules'
      - '/srv/www/main:/www/main'
      - '/srv/www/flyboard:/www/flyboard'
      # confs:
      - './nginx/default:/etc/nginx/conf.d/default.conf'
      - './nginx/main:/etc/nginx/conf.d/main.conf'
      - './nginx/evklid-trainer:/etc/nginx/conf.d/evklid.conf'
      - './nginx/shell:/etc/nginx/conf.d/shell.conf'
      # certs:
      - '/etc/ssl/konstantinov.com.ru.crt:/etc/ssl/konstantinov.com.ru.crt'
      - '/etc/ssl/konstantinov.com.ru.key:/etc/ssl/konstantinov.com.ru.key'
    restart: always
    networks:
      - backend
      - frontend

  php:
    build: ./php/
    container_name: php
    volumes:
      - '/srv/edu-shell:/shell'
    environment: []
    networks:
      - backend
    restart: always

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - 'mysql:db'
#    ports:
#      - '8082:80'
#    environment:
#      - PMA_USER=root
#      - PMA_PASSWORD=password
#      - PHP_UPLOAD_MAX_FILESIZE=100MB
#    networks:
#      - backend
#      - frontend

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - backend

  mongodb:
    image: mongo:3.2
    container_name: mongo_db
    volumes:
      - '/srv/mongo:/data/db'
    restart: always
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
