version: "2"

services:
  eltech:
    build: ./eltech/
    container_name: main
    restart: always

  evklid-trainer:
    build: ./evklid-trainer/
    container_name: evklid
    restart: always

  nginx-proxy:
    build: ./nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  mongodb:
   image: mongo
   container_name: mongodb
   ports:
    - 27017:27017
   volumes:
   - /srv/mongo/evklid-trainer:/data/db
   restart: always

networks:
  default:
    external:
      name: nginx-proxy
