version: "2"

services:
  strassen:
    build: ./strassen/
    environment:
                - VIRTUAL_HOST=strassen.eltech.localhost

  eltech:
    build: ./eltech/
    environment:
                - VIRTUAL_HOST=eltech.localhost

networks:  
  default:
    external:
      name: nginx-proxy
