version: "2"

services:
  eltech:
    build: ./eltech/
    container_name: shell
    restart: always
    volumes:
          - /srv/docker/edu-modules:/www
          - /srv/docker/offline-modules:/www/modules

  evklid-trainer:
    build: ./evklid-trainer/
    container_name: evklid
    restart: always
    volumes:
          - /srv/docker/online-modules/evklid-trainer:/usr/discrete-eltech
    ports:
          - 8888:8888

  atp-system:
      build: ./atp-system/
      container_name: atp-system
      restart: always
      volumes:
          - /srv/docker/online-modules/atp-system:/usr/atp-system
      ports:
          - 8887:8887

  nginx-proxy:
    build: ./nginx/
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  mongodb:
   image: mongo
   container_name: mongodb
   ports:
    - 27017:27017
   volumes:
   - /srv/mongo/evklid-trainer:/data/db
   restart: always

networks:
  default:
    external:
      name: nginx-proxy
